insert into public.opciones (pregunta_id, letra, texto, es_correcta) values
('cap-bace85ae4669', 'b', 'Sí, pero solo el nombre del conductor.', false),
('cap-bace85ae4669', 'c', 'Sí, siempre y cuando esté la tarjeta insertada en el tacógrafo.', true),
('cap-bace85ae4669', 'd', 'Sí, aunque la tarjeta esté fuera del tacógrafo.', false),
('cap-27ff9686488f', 'a', 'Sí.', true),
('cap-27ff9686488f', 'b', 'No.', false),
('cap-27ff9686488f', 'c', 'Es una decisión que depende de cada Estado.', false),
('cap-27ff9686488f', 'd', 'Depende del volumen de operaciones que se realicen anualmente.', false),
('cap-6a1d5d3f56c5', 'a', 'Sí, aunque no estén homologadas.', false),
('cap-6a1d5d3f56c5', 'b', 'No, las hojas deben indicar para qué modelos de tacógrafo están homologadas.', true),
('cap-6a1d5d3f56c5', 'c', 'Sí, cualquier hoja, una vez homologada, debe servir para todos los modelos.', false),
('cap-6a1d5d3f56c5', 'd', 'Sí, incluso para el tacógrafo digital.', false),
('cap-f25f7968bf70', 'a', 'Sobre la palanca del cambio.', false),
('cap-f25f7968bf70', 'b', 'Sobre el grupo cónico.', false),
('cap-f25f7968bf70', 'c', 'Sobre el diferencial.', false),
('cap-f25f7968bf70', 'd', 'Sobre el árbol de transmisión.', true),
('cap-9b1b8e5f6d77', 'a', 'Sobre las ruedas delanteras, siempre.', false),
('cap-9b1b8e5f6d77', 'b', 'Sobre los discos de freno.', false),
('cap-9b1b8e5f6d77', 'c', 'Sobre el tambor de freno.', false),
('cap-9b1b8e5f6d77', 'd', 'Sobre la transmisión.', true),
('cap-a60ea4ae6d79', 'a', 'Sí, y en casi su práctica totalidad se trata de acuerdos de exclusividad.', false),
('cap-a60ea4ae6d79', 'b', 'No, lo que más caracteriza al transporte de mercancías por carretera es la contratación individual de cada viaje.', false),
('cap-a60ea4ae6d79', 'c', 'Prácticamente la única forma de comercialización son los acuerdos estables.', false),
('cap-a60ea4ae6d79', 'd', 'Sí, es habitual que exista algún tipo de acuerdo estable.', true),
('cap-11aa08a61127', 'a', 'No.', false),
('cap-11aa08a61127', 'b', 'No, porque los accidentes siempre son físicos.', false),
('cap-11aa08a61127', 'c', 'No, porque el factor psíquico no afecta al sector del transporte.', false),
('cap-11aa08a61127', 'd', 'Sí, porque la conducción profesional es dada a la aparición de fatiga y estrés.', true),
('cap-a82b9d88eae2', 'a', 'Sí.', true),
('cap-a82b9d88eae2', 'b', 'Sí, pero solo si es en el sentido de la marcha.', false),
('cap-a82b9d88eae2', 'c', 'No, nunca.', false),
('cap-a82b9d88eae2', 'd', 'Sí, pero solo si es en sentido contrario a la marcha del vehículo.', false),
('cap-7d476f8c8c87', 'a', 'No.', false),
('cap-7d476f8c8c87', 'b', 'Sí, pero solo en los discos estándar.', false),
('cap-7d476f8c8c87', 'c', 'Sí.', false),
('cap-7d476f8c8c87', 'd', 'Sí, pero solo en los discos automáticos.', false),
('cap-d89fb0988a7c', 'a', 'No, el Espacio Schengen es más restringido.', false),
('cap-d89fb0988a7c', 'b', 'Sí, son los mismos que forman la Unión Europea.', false),
('cap-d89fb0988a7c', 'c', 'No, la cooperación Schengen es más restringida.', false),
('cap-d89fb0988a7c', 'd', 'Sí, son denominaciones equivalentes.', false),
('cap-9fac1ee96a94', 'a', 'Solo en largos viajes.', false),
('cap-9fac1ee96a94', 'b', 'Sí.', true),
('cap-9fac1ee96a94', 'c', 'No, solo depende del carburante.', false),
('cap-9fac1ee96a94', 'd', 'No, nunca.', false);
