insert into public.temas_teoria (slug, titulo, resumen_md) values
('calidad-servicio', 'Calidad del servicio e imagen de empresa', '- El conductor es la cara visible de la empresa. Su actitud, apariencia y profesionalidad influyen directamente en cómo el cliente percibe la calidad del servicio y la imagen de la marca. - Un servicio de calidad es aquel que cumple lo prometido por la empresa y satisface las necesidades del cliente. Esto incluye la fiabilidad del transporte y la competencia del personal. - El conductor interactúa con diversos interlocutores (clientes, cargadores, descargadores). Una comunicación efectiva y un trato adecuado son cruciales, evitando confrontaciones en situaciones de conflicto. - El buen estado del vehículo y una organización eficiente del trabajo son fundamentales. Esto no solo garantiza la seguridad, sino que también contribuye a la puntualidad y a la percepción de profesionalidad. - Los problemas o litigios tienen un impacto negativo tanto comercial como financiero para la empresa. Prevenirlos mediante un servicio de calidad y una buena gestión es vital. - Herramientas como el IVMS (Intelligent Vehicle Monitoring System) ayudan a la gestión del transporte, permitiendo estimar tiempos de entrega y mejorar la eficiencia. **Lo que más cae:** En el examen se pregunta mucho por la definición de calidad del servicio, entendiendo que es cuando se cumple lo prometido y se satisfacen las necesidades del cliente, alcanzando el nivel que la empresa se propuso. La fiabilidad del transporte, que sea tal como se prometió, es clave. También insisten en que la imagen de marca se forma por muchas fuentes y que la calidad es el factor que más influye, permitiendo diferenciar a la empresa de la competencia. El papel del conductor es fundamental, ya que su apariencia, actitud y competencia (conocimientos y habilidades) son aspectos muy relevantes para la percepción del cliente. Se valora que el conductor sepa saludar, tenga una conducta adecuada y, ante la violencia verbal, no se encare con el agresor. Recuerda que las funciones del conductor van más allá de conducir, incluyendo vigilar el correcto funcionamiento del vehículo. El sistema IVMS se menciona como ayuda para estimar tiempos de entrega. También es importante saber que no se pueden dar primas por carga que comprometan la seguridad en carretera y que la reacción ágil ante incidencias es un punto a favor. La limpieza de vehículos de alimentos la puede hacer la empresa si acredita los productos, y la formación CAP incluye la sensibilización sobre derechos de viajeros con discapacidad.'),
('carga-estiba', 'Carga, estiba y masas', '- El reparto correcto de la carga es fundamental para la seguridad y el rendimiento del vehículo. Una mala distribución o una sobrecarga por eje aumenta el riesgo de accidente y afecta la estabilidad, especialmente en curvas.  - Un centro de gravedad alto disminuye la estabilidad del vehículo y aumenta el riesgo de vuelco en curvas. Es crucial mantenerlo lo más bajo posible y centrado para una conducción segura.  - La estiba es el arte de colocar y asegurar la carga para que no se mueva durante el transporte. Una buena estiba previene movimientos de masa excesivos al frenar y mantiene la estabilidad del vehículo.  - La carga útil es la masa que puede transportar un camión, calculada restando la tara de la Masa Máxima Autorizada. Es vital calcularla correctamente para no exceder los límites y evitar sanciones o riesgos.  - La sobrecarga, especialmente en los ejes, tiene consecuencias graves como daños en el vehículo, neumáticos, dificultad en la conducción y mayor riesgo al frenar. Los vehículos con carga indivisible que superen la MMA necesitan autorización especial.  - El conductor no solo conduce, sino que también supervisa la colocación y acondicionamiento de la carga, especialmente en servicios de paquetería, para asegurar que se respeten las consignas de seguridad.  **Lo que más cae:** En el examen se pregunta mucho sobre las consecuencias de una incorrecta distribución de la carga, que siempre provoca un aumento del riesgo de accidente y afecta directamente a la seguridad y al rendimiento del vehículo. Es fundamental entender que la estiba es el arte de colocar la carga para transportarla de la mejor manera, evitando movimientos excesivos de masas, especialmente al frenar. Otro punto clave es el centro de gravedad: un incremento de su altura siempre disminuye la estabilidad del camión e incrementa el riesgo en las curvas. También se insiste en la definición de carga útil, que es la masa que puede transportar un camión restando su tara de la Masa Máxima Autorizada. Las consecuencias de la sobrecarga son recurrentes, como la necesidad de más cambios y una subida más lenta en pendientes, o los daños en el eje de dirección y neumáticos, además de sus efectos negativos al frenar. Recuerda que una carga indivisible es aquella que no puede dividirse sin coste o riesgo de daños, y si supera la Masa Máxima Permitida, necesita una autorización especial. Finalmente, ten presente que el conductor tiene la obligación de supervisar la colocación y acondicionamiento de la carga, y que el vehículo jaula se usa para animales vivos.'),
('conduccion-eficiente', 'Conducción eficiente y consumo', '- La anticipación al tráfico y mantener una distancia de seguridad adecuada son cruciales para una conducción fluida. Esto permite aprovechar la inercia del vehículo y evitar frenadas y aceleraciones innecesarias, optimizando el consumo de carburante.
- Utiliza siempre la relación de marchas más alta posible que permitan la velocidad y las condiciones de la vía. Busca mantener el motor en la zona de par máximo, que suele estar indicada como la "zona verde" en el cuentarrevoluciones, para un menor consumo.
- Una velocidad constante y una conducción sin brusquedades reducen significativamente el gasto de carburante. Evita acelerones fuertes y frenazos repentinos, ya que son momentos de alto consumo y desgaste mecánico.
- La presión correcta de los neumáticos es fundamental; una presión inadecuada aumenta la resistencia a la rodadura y, por tanto, el consumo. También influyen factores como la aerodinámica del vehículo, por ejemplo, manteniendo las ventanillas cerradas.
- Conocer las resistencias que afectan al movimiento del camión, como la aerodinámica, la de rodadura y la de pendiente, te ayudará a adaptar tu conducción. Minimizar estas resistencias es clave para la eficiencia.
- Nunca bajes pendientes en punto muerto; esta práctica es peligrosa y no ahorra carburante, además de ser una medida de ahorro equivocada. Es mejor usar una marcha larga para aprovechar el freno motor y la inercia.

**Lo que más cae:** En el examen se pregunta mucho sobre las ventajas de usar la relación de marchas más alta posible, que son menor consumo, menos contaminación acústica y menor desgaste mecánico. También es recurrente la indicación de la zona verde del cuentarrevoluciones como la de menor consumo, y que conducir en la zona de máximo par motor aprovecha mejor el carburante. Se insiste en que el perfil de la carretera es un dato importante para elegir la marcha. Otro punto clave son las resistencias que intervienen en el movimiento del vehículo: la aerodinámica, la de rodadura y la de pendiente, siendo la aerodinámica la fuerza que se opone al avance por el aire y que influye en el consumo y la estabilidad. Es importante saber que el tipo de sistema de frenado no influye en el consumo. Para reducir el gasto, en llano hay que mantener el acelerador poco presionado, y es una medida equivocada bajar las pendientes en punto muerto. Se valora la reducción de la velocidad media de circulación por el menor consumo y ruido, y mantener las ventanillas subidas en carretera. Además de reducir el consumo, la conducción económica disminuye los desgastes mecánicos. También se pregunta que la energía cinética es mayor cuanto mayor sea la masa del vehículo, y que las cajas de cambio manuales suelen consumir menos que las automáticas.'),
('entorno-economico', 'Entorno económico y organización', '- El transporte por carretera es el modo más empleado en España, destacando por su flexibilidad y capacidad de generar empleo. Compite con otros modos ofreciendo soluciones puerta a puerta, lo que lo hace ideal para la mayoría de las mercancías.
- Las actividades se dividen en transporte por cuenta ajena, para terceros, y por cuenta propia, para las necesidades internas de la empresa. También existen actividades auxiliares como los transitarios, que organizan transportes internacionales.
- Las empresas pueden ser individuales, sociedades anónimas (SA) o de responsabilidad limitada (SL). Las SA, por ejemplo, adquieren personalidad jurídica al inscribirse en el Registro Mercantil y requieren un capital social mínimo de 60.000 euros.
- El sector evoluciona hacia la diversificación de servicios, la intermodalidad y la subcontratación, adaptándose a especializaciones como cisternas o temperaturas controladas. Esto busca eficiencia y respuesta a las demandas específicas del mercado.
- La gestión económica es vital, considerando el precio usual del transporte según el Observatorio de Costes y la importancia de una buena gestión comercial para optimizar ingresos. Los seguros de mercancías, aunque los pague el consumidor, son un coste repercutible.

**Lo que más cae:** En el examen, suelen preguntar mucho sobre la constitución y características de las sociedades. Por ejemplo, cuándo adquiere personalidad jurídica una sociedad anónima, que es al inscribir la escritura pública en el Registro Mercantil, o el capital social mínimo de 60.000 euros para una SA. También es frecuente que pregunten por la denominación de una sociedad de responsabilidad limitada, que no puede coincidir con otra. Otro tema recurrente son las funciones del personal administrativo, como realizar operaciones de contabilidad o elaborar nóminas. No olvides que el transporte por carretera es el que más empleo genera y que los centros de transporte y logística están contemplados en la Ley de Ordenación de los Transportes Terrestres (LOTT). Respecto a los costes, se considera precio usual el coste medio del Observatorio de Costes, y si un consumidor contrata un seguro de mercancías, él asume el coste, aunque el transportista lo repercuta. También preguntan por los transitarios, que organizan transportes internacionales, y por las Juntas Arbitrales del Transporte, que presumen sometimiento si la controversia no excede los 15.000 euros. Ten en cuenta que las toneladas-kilómetro internacionales en España son casi todas de servicio público y que las sucursales de una empresa CAP deben ser controladas periódicamente por la Administración.'),
('frenado-seguridad', 'Frenado y dispositivos de seguridad', '- El sistema de frenado es vital; hay que conocer los límites de frenos y ralentizadores. Úsalos combinados, sobre todo en descensos, para evitar sobrecalentamiento y pérdida de eficacia.
- Los dispositivos electrónicos como ABS, ESP, AEBS y TCS son ayudas cruciales. Mejoran el control de tracción, estabilidad, previenen bloqueos y asisten en frenadas de emergencia, aumentando la seguridad activa.
- La seguridad se divide en activa y pasiva. La activa busca evitar el accidente, la pasiva, como el cinturón, minimiza daños. Algunos elementos activos requieren tu acción.
- Es clave saber reaccionar ante situaciones críticas. Si las ruedas se bloquean al frenar, levanta progresivamente el pedal. Un reventón de neumático se detecta por un fuerte tirón en la dirección.
- La adherencia y el rozamiento son fundamentales para un frenado efectivo. El tipo y la presión de los neumáticos influyen directamente en el agarre con la calzada, afectando la distancia de frenado.
- La suspensión del camión influye directamente en su estabilidad y comportamiento. Es un elemento fundamental para el control del vehículo en diferentes condiciones de carga y terreno.

**Lo que más cae:** En el examen, se pregunta mucho sobre cómo detectar un reventón de neumático, que se nota por un fuerte tirón de la dirección hacia un lado. Es recurrente la pregunta sobre el efecto "fading", dejando claro que no provoca una disminución automática de la velocidad, sino una pérdida de eficacia del freno. Se insiste en la diferencia entre seguridad activa y pasiva, y qué elementos requieren la acción física del conductor, siendo algunos de seguridad activa. La influencia de la suspensión en la estabilidad del camión y cómo se nota el subviraje (el volante ofrece menos resistencia) son preguntas habituales. Los sistemas ADAS son un tema fuerte, incluyendo las tecnologías que utilizan (como el láser para obtener datos de objetos) y su funcionamiento, como el sistema avanzado de frenado de emergencia que actúa ante una colisión inminente. Los factores que influyen en el grado de rozamiento, como la presión y el tipo de neumáticos, son importantes. Los ralentizadores, especialmente los retardadores y el freno eléctrico (que usa corrientes magnéticas y mantiene las revoluciones sin rozamiento), aparecen con frecuencia. También se pregunta sobre el sistema ASR como control de tracción y el funcionamiento de los frenos ABS, que reducen la distancia en mojado, no tanto en seco y pueden aumentarla en grava o nieve. Saber qué hacer si las ruedas se bloquean (levantar el pedal), entender la fuerza de adherencia y los pares de viraje (fuerzas que intentan girar el camión) son puntos clave. La transferencia de masas en la frenada y su efecto en el agarre de las ruedas también es un tema a dominar.'),
('motor-transmision', 'El vehículo: motor y transmisión', '- El motor genera par y potencia, que son fundamentales para el movimiento del vehículo. El par es la fuerza de giro que produce el motor, mientras que la potencia es la cantidad de trabajo que puede desarrollar en una unidad de tiempo. Ambos se relacionan directamente con el rendimiento del camión.
- Para optimizar el consumo de carburante y el rendimiento, es crucial conocer las curvas de par, potencia y consumo específico del motor. Esto permite al conductor mantener el motor en su zona óptima de revoluciones, evitando esfuerzos innecesarios o un consumo excesivo.
- La transmisión, a través de la caja de cambios, es la encargada de adaptar el par y la potencia del motor a las ruedas. Las diferentes relaciones de cambio permiten seleccionar la fuerza o la velocidad más adecuada para cada situación de conducción, ya sea para arrancar, subir una pendiente o circular por autopista.
- Los diagramas de cobertura de las relaciones de la caja de cambios muestran el rango de velocidades que se pueden alcanzar con cada marcha. Entender estos diagramas ayuda a elegir la marcha correcta para mantener el motor en su régimen de funcionamiento más eficiente, evitando que se agote o se revolucione en exceso.
- En el movimiento de un camión intervienen diversas fuerzas, como la fuerza motriz generada por el motor, la fuerza de adherencia entre los neumáticos y la calzada, la fuerza de gravedad y las fuerzas resistentes (aerodinámica, rodadura). Para que el vehículo se mueva, la fuerza motriz debe superar la suma de las fuerzas resistentes.

**Lo que más cae:** En el examen se pregunta mucho sobre la potencia del motor, entendiéndola como el trabajo que desarrolla en un tiempo, y su relación con el par motor y las revoluciones. También es recurrente la importancia de saltar velocidades, tanto al subir como al bajar marchas o pendientes, siempre que sea necesario para optimizar el rendimiento. Se insiste en las fuerzas que intervienen en el movimiento del camión, como la fuerza motriz, la de adherencia y la de gravedad, y la necesidad de que la fuerza del motor supere las resistencias para iniciar el movimiento. Otro punto clave es el par motor, su medición en newton-metro (Nm) y la necesidad de generar par al ralentí para vencer rozamientos. Además, se pregunta sobre cómo el mantenimiento (filtros, aceites) y la relación de marchas seleccionada afectan al consumo de carburante, y las pérdidas de potencia por un mal funcionamiento de las válvulas. Finalmente, es importante saber que las pérdidas energéticas en la transmisión se deben principalmente al rozamiento de sus elementos.'),
('prevencion-riesgos', 'Prevención de riesgos (robos, tráfico ilegal)', '- La prevención de robos y delincuencia en el transporte implica estar siempre alerta, asegurar bien la carga y el vehículo, y conocer las rutas de riesgo. Es fundamental no dejar el vehículo desatendido en lugares peligrosos y revisar siempre que las puertas y cierres estén bien.
- El tráfico ilegal de personas o mercancías tiene graves consecuencias legales para el conductor y el transportista. Es tu responsabilidad asegurarte de que no transportas nada ni a nadie sin la documentación o autorización adecuada, especialmente al cruzar fronteras.
- Tanto el empresario como el trabajador tienen obligaciones claras en prevención de riesgos laborales. El empresario debe evitar los riesgos que se puedan evitar, y el trabajador debe usar correctamente los equipos de protección individual.
- El Espacio Schengen facilita la circulación, pero también implica una cooperación policial intensa para combatir la delincuencia organizada. Los transportistas tienen la obligación de proporcionar datos de pasajeros en rutas extracomunitarias y de verificar su documentación.
- Ante un incendio en el vehículo, es crucial saber cómo actuar. Las medidas preventivas incluyen el buen mantenimiento y la revisión de los sistemas eléctricos, y el uso correcto de extintores, eligiendo el agente extintor adecuado para cada tipo de fuego.
- La colaboración, incluso involuntaria, en el transporte de productos prohibidos o personas sin papeles puede ser considerada delito de contrabando o infracción grave de extranjería. Las multas son muy elevadas y las consecuencias penales, serias.

**Lo que más cae:** En el examen se pregunta mucho sobre las obligaciones de prevención de riesgos laborales, tanto del empresario, que debe evitar los riesgos evitables, como del trabajador, que tiene que usar los equipos de protección. También es recurrente la prevención de incendios, donde casi siempre todas las medidas son correctas, y la importancia de usar el extintor adecuado o refrigerar el combustible. Sobre el tráfico ilegal, insisten en que las infracciones muy graves de extranjería se sancionan con multas de 10.001 a 100.000 euros, y que no comprobar pasaportes o visados conlleva multas de 5.000 a 10.000 euros por viajero. Recuerda que la responsabilidad recae en los transportistas y conductores. El Espacio Schengen abarca países de Europa y su Sistema de Información (SIS) busca preservar el orden y la seguridad. Los datos de viajeros de rutas fuera de Schengen deben borrarse en 24 horas y la información se pide para transporte aéreo, marítimo o terrestre. El delito de contrabando se da con drogas tóxicas o con mercancías valoradas en más de 12.000 euros, y puede implicar al conductor. También preguntan si un sistema IVMS puede llevar un botón antipánico (sí) y que los accidentes en mantenimiento de vehículos particulares no son un riesgo asociado al transporte. Los equipos de protección contra riesgos medios son de Categoría II.'),
('reglamentacion-documentos', 'Documentos y reglamentación del transporte', '- Para ejercer el transporte profesional, necesitas títulos y autorizaciones específicas, como la licencia comunitaria para el ámbito internacional. Siempre debes llevar a bordo los documentos que acrediten la legalidad del transporte, el vehículo y la mercancía. Es fundamental conocer las restricciones de circulación que puedan afectar a tu ruta o tipo de carga. 
- El contrato de transporte establece las obligaciones entre cargador y transportista, y se plasma en documentos como la carta de porte. Es crucial entender las responsabilidades de cada parte, especialmente en caso de incidencias o retrasos en la entrega. Las Juntas Arbitrales del Transporte son una vía para resolver controversias si no se ha pactado otra cosa. 
- En el transporte internacional, además de la licencia comunitaria, entran en juego convenios como el CMR, que regula la carta de porte internacional y las responsabilidades. También hay normativas específicas para mercancías peligrosas o perecederas, como el acuerdo ATP, que define los tipos de vehículos frigoríficos. 
- Existen exenciones de autorización para ciertos transportes, como los realizados con vehículos de menos de tres ruedas o aquellos que llevan una grúa unida de modo permanente si se dedican exclusivamente a dar soporte a dicho instrumento. El transporte privado complementario también tiene sus propios requisitos para no necesitar autorización. 
- Las tasas por el uso de la infraestructura vial y el paso de fronteras son aspectos económicos y administrativos que todo conductor profesional debe tener en cuenta. Los transitarios pueden facilitar la gestión de estos trámites, especialmente en operaciones complejas o internacionales.

**Lo que más cae:** En el examen, suelen preguntar mucho sobre el Certificado de Aptitud Profesional (CAP): que la formación continua es cada cinco años, que los exámenes se convocan al menos seis veces al año y que es imprescindible junto al permiso de conducir para vehículos C1 o C1+E, buscando mejorar la seguridad vial y la seguridad del conductor. También es frecuente que pregunten por el acuerdo ATP, como qué significa un vehículo FRF (frigorífico reforzado clase F). Sobre el tránsito de la Unión, recuerda que la garantía puede ser individual o global, que el transportista es responsable de presentar las mercancías en la aduana de destino, que es donde finaliza el régimen. Las exenciones de autorización son importantes: vehículos de menos de tres ruedas, los que llevan una grúa permanente si es para su soporte, o el transporte privado complementario, que no debe ser la actividad principal de la empresa. En transporte internacional, se puede circular con cabeza tractora y semirremolque matriculados en países diferentes de la UE. Las Juntas Arbitrales del Transporte son clave: pueden acordar el depósito de mercancías si hay impedimentos para la entrega y el cargador no da nuevas instrucciones, y si no se ha pactado una, la elige el demandante. No olvides que la normativa de transporte de animales vivos se aplica a vertebrados, y que la placa TIR es azul con las letras TIR.'),
('salud-ergonomia', 'Salud, ergonomía y aptitud', '- La ergonomía busca adaptar el puesto de trabajo al conductor para eliminar riesgos físicos y mejorar el bienestar. Esto incluye ajustar el asiento correctamente antes de empezar a conducir y mantener una buena postura al volante. 
- Es fundamental cuidar la condición física y mental. Una alimentación equilibrada, moderando grasas, y el respeto del ciclo de actividad y reposo son clave para evitar la fatiga y el estrés. 
- El consumo de alcohol, ciertos medicamentos o cualquier otra sustancia puede alterar gravemente el comportamiento y la capacidad de reacción. Siempre hay que informarse de los efectos secundarios de los fármacos antes de conducir. 
- La fatiga y el estrés son riesgos importantes que aumentan con trayectos desconocidos o la falta de descanso adecuado. Reconocer sus síntomas y prevenirlos es vital para la seguridad en la carretera. 
- La manipulación de cargas requiere técnicas correctas para evitar lesiones, especialmente al inclinar el cuerpo en posiciones inestables durante mucho tiempo. El uso de equipos de protección individual es esencial en ciertas tareas. 
- La prevención de riesgos laborales es una responsabilidad compartida entre el empresario y el trabajador. Su objetivo es evitar los riesgos que se pueden eliminar y evaluar los que no son evitables. 

**Lo que más cae:** En el examen se pregunta mucho sobre la ergonomía y sus beneficios, como la eliminación de riesgos físicos, el incremento del bienestar y la prevención de problemas de salud, dejando claro que no busca ajustar la remuneración. Recuerda que el asiento se regula antes de iniciar el recorrido. También insisten en la importancia de una alimentación equilibrada, destacando que hay que moderar el consumo de carnes grasas y que los hidratos de carbono dan energía. Otro punto recurrente es la prevención de riesgos laborales, que es obligación tanto del empresario como del trabajador, y busca evitar riesgos y evaluar los que no se pueden evitar. Ten en cuenta que encender un cigarrillo es una distracción interna. Sobre medicamentos, siempre hay que informarse de sus efectos secundarios. La fatiga aumenta en trayectos poco conocidos y el estrés tiene múltiples soluciones. Además, se pregunta sobre accidentes frecuentes como las caídas al mismo nivel, y que la comida y la complexión influyen en el nivel de alcohol en sangre. Las enfermedades profesionales son las relacionadas con la actividad y con alta ocurrencia.'),
('seguridad-vial-accidentes', 'Seguridad vial, accidentes y primeros auxilios', '- La seguridad vial exige anticipar riesgos del tráfico, adaptándose a las condiciones de la vía, el clima y el comportamiento de otros usuarios. Es crucial planificar los viajes con antelación y saber cuándo aplazarlos o cancelarlos por condiciones meteorológicas extremas.
- Como conductor profesional, debes ser consciente de los peligros de las distracciones al volante, como el uso de dispositivos electrónicos o comer, y de los comportamientos agresivos. Presta especial atención a usuarios vulnerables como peatones, ciclistas y motoristas, que son más frágiles y requieren un margen de seguridad adicional.
- En caso de accidente, tu prioridad es evaluar la situación para evitar nuevos peligros, proteger la zona y alertar a los servicios de emergencia. Luego, si es seguro y estás protegido con guantes y mascarillas, asiste a los heridos aplicando primeros auxilios básicos, sin moverlos a menos que sea estrictamente necesario.
- Los accidentes de tráfico son el principal componente de la siniestralidad en el transporte profesional y suelen confluir en ellos varias causas. Estos siniestros conllevan graves consecuencias humanas, materiales y económicas para los afectados y la sociedad en general.
- Para una conducción segura, es fundamental respetar las normas de circulación y mantener siempre una distancia de seguridad adecuada con el vehículo que te precede. Esto te proporciona el margen de reacción necesario ante cualquier imprevisto o reducción brusca de velocidad.
- La declaración amistosa de accidente es una herramienta clave en caso de siniestro sin heridos graves. Es fundamental que esté correctamente cumplimentada y firmada por ambos conductores para agilizar los trámites y evitar problemas futuros.

**Lo que más cae:** En el examen, se pregunta mucho sobre cómo actuar en un accidente: siempre hay que protegerse usando guantes y mascarillas al auxiliar a los heridos, y nunca sacar a una persona del lugar del accidente como primera actuación, salvo peligro inminente. También insisten en que los accidentes de tráfico son el principal componente de la siniestralidad entre conductores profesionales, y que suelen confluir varias causas en ellos, no por falta de experiencia. Los factores que aparecen con más frecuencia en los accidentes son la distracción, la velocidad inadecuada y el consumo de alcohol. Es fundamental respetar las normas de circulación y no pegarse al vehículo que nos precede, ya que nos deja sin margen de reacción. La declaración amistosa de accidente es muy importante, debe estar firmada por ambos conductores y anotarse todos los datos correctamente. Recuerda que los accidentes conllevan graves gastos para la economía de los afectados y producen con frecuencia lesiones físicas serias, como traumatismos craneoencefálicos o lesiones medulares. También se menciona que el número de accidentes ha disminuido en los últimos 30 años tanto en zonas urbanas como interurbanas.'),
('tiempos-tacografo', 'Tiempos de conducción y tacógrafo', '- Los tiempos de conducción diarios no pueden superar las 9 horas, ampliables a 10 horas dos veces por semana. El descanso diario regular es de 11 horas, que se puede dividir o reducir bajo ciertas condiciones. Es crucial respetar estos límites para la seguridad y la normativa.
- El tacógrafo, ya sea analógico o digital, es la herramienta clave para registrar la actividad del conductor. Registra automáticamente la velocidad, los kilómetros recorridos y los tiempos de conducción, trabajo, disponibilidad y descanso. Su uso correcto es responsabilidad del conductor.
- La tarjeta de conductor es personal e intransferible, y solo se debe tener una, incluso si se trabaja para varias empresas. Al cambiar de vehículo o al inicio y final de la jornada, es fundamental introducir los datos correctos en el tacógrafo, como las lecturas del cuentakilómetros y los lugares de inicio y fin.
- Las recuperaciones de los descansos semanales reducidos deben hacerse en un solo bloque, unido a un período de descanso diario de al menos 9 horas. La semana de conducción se cuenta de lunes a domingo, y no se pueden superar las 56 horas de conducción en una semana ni 90 horas en dos semanas consecutivas.
- En caso de avería del tacógrafo, es obligatorio repararlo tan pronto como las circunstancias lo permitan. Mientras tanto, el conductor debe anotar manualmente sus actividades en el reverso del disco o en una hoja de registro temporal. La manipulación del tacógrafo es una infracción muy grave con duras sanciones.

**Lo que más cae:** En el examen, se pregunta mucho sobre los plazos de prescripción de las infracciones graves, que es de un año. También es recurrente la definición de la semana de conducción, que va del lunes a las 00:00 al domingo a las 24:00. Presta especial atención a cómo se recuperan los descansos semanales reducidos: siempre en un solo bloque y unido a un descanso diario de al menos 9 horas. Es fundamental saber qué datos hay que anotar manualmente en los discos-diagrama del tacógrafo analógico, como las lecturas del cuentakilómetros al inicio y al final, y los lugares de comienzo y fin. No olvides que, en caso de avería del tacógrafo, la reparación es obligatoria tan pronto como sea posible. También se pregunta sobre el funcionamiento del tacógrafo digital, cómo se extrae la tarjeta de conductor y que solo se puede tener una tarjeta por conductor. Ten claro que la planificación de la ruta debe asegurar que no se superen los tiempos máximos de conducción y que los vehículos de la Administración Pública pueden estar exentos si realizan actividades propias. Finalmente, recuerda que el tacógrafo registra automáticamente la velocidad y que los vehículos nuevos deben llevar tacógrafo digital.')
on conflict (slug) do update set
    titulo = excluded.titulo,
    resumen_md = excluded.resumen_md,
    updated_at = now();
